version: '3.8'
services:
  vocbench3:
    image: vocbench3:12.1.0
    build:
      context: 12.1.0
    ports:
    - "1979:1979"
    volumes:
     - type: bind
       source: ./volumes/stdata
       target: /opt/vocbench3/data
    links:
    - graphdb
  graphdb:
    image: graphdb-with-st-sails:10.4.1
    build:
      context: ./helpers/graphdb-with-st-sails
      args:
        st_version: "12.1"
        vb_version: "12.1.0"
        gdb_version: "10.4.1"
    ports:
     - "127.0.0.1:7200:7200"
    volumes:
     - type: bind
       source: ./volumes/gdbhome
       target: /opt/graphdb/home